
[theme]
base = "light"
primaryColor = "#1976D2"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#E3F2FD"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
